language: go
go:
  - tip
sudo: false

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/drivernation/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci -v -tags test